import { createRemoteJWKSet, jwtVerify } from "npm:jose@5.10.0";
const PROJECT_URL=Deno.env.get("SUPABASE_URL")!;const SECRET_KEYS=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")??"{}");const SECRET_KEY=SECRET_KEYS.default??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const USER_ID="0b502819-c06b-49c8-8529-981eaf9de4b3";const EXPECTED_AUDIENCE="personal-os-supabase";const EXPECTED_REPOSITORY="MIR-Korea/fatsecret-notion-sync";const EXPECTED_REPOSITORY_ID="1354323092";const EXPECTED_OWNER_ID="323885189";const EXPECTED_REF="refs/heads/main";const ALLOWED_WORKFLOWS=new Set(["MIR-Korea/fatsecret-notion-sync/.github/workflows/sync.yml@refs/heads/main","MIR-Korea/fatsecret-notion-sync/.github/workflows/backfill-supabase.yml@refs/heads/main"]);const JWKS=createRemoteJWKSet(new URL("https://token.actions.githubusercontent.com/.well-known/jwks"));
type D={date:string;calories:number;carbs:number;protein:number;fat:number;food_count?:number};type E={fatsecret_id:string;date:string;food:string;meal:string;calories:number;carbs:number;protein:number;fat:number};
function json(s:number,b:Record<string,unknown>){return Response.json(b,{status:s,headers:{"Cache-Control":"no-store"}})}function n(v:unknown,m:number){return typeof v==="number"&&Number.isFinite(v)&&v>=0&&v<=m}function vd(v:unknown):v is D{if(!v||typeof v!=="object")return false;const d=v as Record<string,unknown>;return typeof d.date==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(d.date)&&n(d.calories,30000)&&n(d.carbs,5000)&&n(d.protein,5000)&&n(d.fat,5000)}function ve(v:unknown):v is E{if(!v||typeof v!=="object")return false;const e=v as Record<string,unknown>;return typeof e.fatsecret_id==="string"&&e.fatsecret_id.length>0&&typeof e.date==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(e.date)&&typeof e.food==="string"&&typeof e.meal==="string"&&n(e.calories,10000)&&n(e.carbs,2000)&&n(e.protein,2000)&&n(e.fat,2000)}
async function api(table:string,body:any,conflict:string,method="POST",query=""){const r=await fetch(`${PROJECT_URL}/rest/v1/${table}${query?`?${query}`:`?on_conflict=${encodeURIComponent(conflict)}`}`,{method,headers:{apikey:SECRET_KEY,"Authorization":`Bearer ${SECRET_KEY}`,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=representation"},body:method==="GET"?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(`${table}:${r.status}`);return method==="GET"?await r.json():await r.json()}
Deno.serve(async req=>{if(req.method!=="POST")return json(405,{error:"method_not_allowed"});if(!SECRET_KEY)return json(500,{error:"server_not_configured"});const a=req.headers.get("authorization")??"";if(!a.startsWith("Bearer "))return json(401,{error:"missing_identity_token"});try{const{payload}=await jwtVerify(a.slice(7),JWKS,{issuer:"https://token.actions.githubusercontent.com",audience:EXPECTED_AUDIENCE,algorithms:["RS256"]});if(payload.repository!==EXPECTED_REPOSITORY||String(payload.repository_id)!==EXPECTED_REPOSITORY_ID||String(payload.repository_owner_id)!==EXPECTED_OWNER_ID||payload.ref!==EXPECTED_REF||!ALLOWED_WORKFLOWS.has(String(payload.job_workflow_ref)))return json(403,{error:"untrusted_workflow"})}catch{return json(401,{error:"invalid_identity_token"})}
let b:any;try{b=await req.json()}catch{return json(400,{error:"invalid_json"})}const now=new Date().toISOString();try{if(b.get_checkpoint===true){const r=await api("pos_backfill_checkpoint",null,"","GET",`user_id=eq.${USER_ID}&job=eq.fatsecret_full&select=last_completed_date`);return json(200,{ok:true,last_completed_date:r[0]?.last_completed_date??null})}if(b.snapshot===true){
if(!Array.isArray(b.days)||!b.days.length||b.days.length>14||!b.days.every(vd)||!Array.isArray(b.entries)||b.entries.length>200||!b.entries.every(ve))return json(400,{error:"invalid_snapshot"});
const dates=new Set(b.days.map((d:D)=>d.date));const ids=new Set(b.entries.map((e:E)=>e.fatsecret_id));
if(dates.size!==b.days.length||ids.size!==b.entries.length||b.entries.some((e:E)=>!dates.has(e.date)))return json(400,{error:"invalid_snapshot"});
for(const d of b.days){const entries=b.entries.filter((e:E)=>e.date===d.date);if(d.food_count!==entries.length||["calories","carbs","protein","fat"].some(k=>Math.abs(d[k]-entries.reduce((sum:number,e:any)=>sum+e[k],0))>0.02))return json(400,{error:"inconsistent_snapshot"});}
const r=await fetch(PROJECT_URL+"/rest/v1/rpc/pos_apply_fatsecret_snapshot",{method:"POST",headers:{apikey:SECRET_KEY,Authorization:"Bearer "+SECRET_KEY,"Content-Type":"application/json"},body:JSON.stringify({p_user_id:USER_ID,p_days:b.days,p_entries:b.entries})});if(!r.ok)throw new Error("snapshot_write:"+r.status);return json(200,await r.json());
}
let ud=0,ue=0;if(b.days!==undefined){if(!Array.isArray(b.days)||!b.days.length||b.days.length>14||!b.days.every(vd))return json(400,{error:"invalid_days"});const rows=b.days.map((d:D)=>({user_id:USER_ID,entry_date:d.date,calories:d.calories,carbs_g:d.carbs,protein_g:d.protein,fat_g:d.fat,source:"fatsecret",source_updated_at:now,synced_at:now}));await api("pos_nutrition_daily",rows,"user_id,entry_date,source");ud=rows.length}if(b.entries!==undefined){if(!Array.isArray(b.entries)||b.entries.length>200||!b.entries.every(ve))return json(400,{error:"invalid_entries"});if(b.entries.length){const rows=b.entries.map((e:E)=>({user_id:USER_ID,fatsecret_id:e.fatsecret_id,entry_date:e.date,food:e.food,meal:e.meal,calories:e.calories,carbs_g:e.carbs,protein_g:e.protein,fat_g:e.fat,source:"fatsecret",synced_at:now}));await api("pos_nutrition_food_entries",rows,"user_id,fatsecret_id");ue=rows.length}}if(typeof b.checkpoint_date==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(b.checkpoint_date)){await api("pos_backfill_checkpoint",{user_id:USER_ID,job:"fatsecret_full",last_completed_date:b.checkpoint_date,updated_at:now},"user_id,job")}if(!ud&&!ue&&!b.checkpoint_date)return json(400,{error:"empty_payload"});return json(200,{ok:true,upserted:ud,upserted_entries:ue,checkpoint:b.checkpoint_date??null})}catch(e){console.error(e);return json(502,{error:"database_write_failed"})}});
